add network module
maximgadelev/tinkoff-project pull request #14
Opened 2022-04-08 14:11 UTC by maximgadelev

2022-04-08 20:30 UTC, Hukumister requested changes

2022-04-08 20:30 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/di/DIContainer.kt
> +        .addConverterFactory(GsonConverterFactory.create()).build()
Лучше Gson не использовать, эта устаревшая лита. Давай лучше на Moshi заменим

2022-04-08 20:30 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/network/BaseInterceptor.kt
> +class BaseInterceptor : Interceptor {
Пока убери это, как понадобится тогда будем писать Interceptorы

2022-04-08 20:30 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/di/DIContainer.kt
> +    factory<OkHttpClient> { provideOkHttpClient(get()) }
OkHttpClient тоже давай сделаем single

2022-04-08 21:41 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/network/BaseInterceptor.kt
> +class BaseInterceptor : Interceptor {
done

2022-04-08 21:41 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/di/DIContainer.kt
> +        .addConverterFactory(GsonConverterFactory.create()).build()
done

2022-04-08 21:41 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/di/DIContainer.kt
> +    factory<OkHttpClient> { provideOkHttpClient(get()) }
done

2022-04-12 11:52 UTC, Hukumister approved these changes

2022-04-12 18:02 UTC, merged