Add product and promotions display
maximgadelev/tinkoff-project pull request #15
Opened 2022-04-13 15:45 UTC by maximgadelev

2022-04-20 11:48 UTC, Hukumister requested changes

2022-04-20 11:48 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/data/mapper/ResponseMapper.kt
> +                productResponse.img[0],
Что произойдет если вдруг бэк пришлет пустой список картинок?)

2022-04-20 11:48 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/data/response/Characteristic.kt
> +class Characteristic
Точно нужен пустой класс?

2022-04-20 11:48 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/data/response/ProductResponse.kt
> +    val rating: Any?
Давай избегать Any в моделях, это может привести к капец какие сложностям

2022-04-20 11:48 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/cart/ui/CartFragmentViewModel.kt
> +    sealed class Event {
Вынести в отедельный файл рядом с CartFragmentViewModel

2022-04-20 11:48 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/common/mapper/EntityMapper.kt
> +        return string.replaceRange(string.length / 2 until string.length, "..")
textView сам умеет так текст обрезать, погугли как, функция лишняя

2022-04-20 11:48 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/favorites/ui/FavoritesViewModel.kt
> +                eventChannel.send(Event.ErrorEvent("Server is blocked"))
Пока давай избегать текстовок в ошибках пока просто можно сделать ErrorEvent как object и на UI показывать общий диалог на всех экранах

2022-04-20 11:48 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/main/ui/MainFragment.kt
> +        lifecycleScope.launchWhenStarted {
Тестил что будет если Активити пересоздастся, эти методы отрабатывают норм?

2022-04-20 11:48 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/main/ui/MainFragment.kt
> +            setTitle("Сервер недоступен")
Строки в коде, низя так делать!!! В ресурсы все строки

2022-04-20 16:39 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/data/response/ProductResponse.kt
> +    val rating: Any?
А,это я накосячил,просто автоматом джсон в объект перевел,а там рейтинг Null.

2022-04-20 21:22 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/data/mapper/ResponseMapper.kt
> +                productResponse.img[0],
Done

2022-04-20 21:23 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/data/response/Characteristic.kt
> +class Characteristic
Да,moshi требует beginObject просто пока в charasteristic полей нет,потому шо в json пусто

2022-04-20 21:23 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/data/response/ProductResponse.kt
> +    val rating: Any?
done

2022-04-20 21:23 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/cart/ui/CartFragmentViewModel.kt
> +    sealed class Event {
done

2022-04-20 21:23 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/common/mapper/EntityMapper.kt
> +        return string.replaceRange(string.length / 2 until string.length, "..")
done

2022-04-20 21:23 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/favorites/ui/FavoritesViewModel.kt
> +                eventChannel.send(Event.ErrorEvent("Server is blocked"))
done

2022-04-20 21:23 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/main/ui/MainFragment.kt
> +        lifecycleScope.launchWhenStarted {
Да,вроде все пашет

2022-04-20 21:23 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/main/ui/MainFragment.kt
> +            setTitle("Сервер недоступен")
done

2022-04-28 13:59 UTC, Hukumister approved these changes

2022-04-28 14:23 UTC, merged