add CatalogFragment
maximgadelev/tinkoff-project pull request #16
Opened 2022-04-14 15:02 UTC by MariaDimukhametova

2022-04-14 15:39 UTC, maximgadelev requested changes

2022-04-14 15:39 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/entity/Category.kt
> +) : DisplayableItem, ComparableItem
Это класс сущности,а не класс,который наследуется от ComparableItem,являющийся ui слоем.Ты должна перемапить объект этого класса в объект наследника ComparableItem

2022-04-14 15:39 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/catalog/utils/DisplayableItem.kt
> +interface DisplayableItem {
Не понимаю, зачем нам пустой интерфейс

2022-04-14 15:39 UTC, maximgadelev commented on app/build.gradle
> +
т.к адаптер делегейт не используем, это убираем

2022-04-14 15:39 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/catalog/presentation/ui/CategoryItemProvider.kt
> +}
Itemprovider должен хоть какие-то категории возвращать, сделай тестовую имплементацию в stubApi пока,чтобы наглядно было видно.

2022-04-14 15:39 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/catalog/presentation/ui/CategoryItemProvider.kt
> +}
И будет принимать лист Category, а возвращать CategoryItem.Category мапим в CategoryItem с помощью мапера.
Посмотри,как все делается, у меня

2022-04-14 15:39 UTC, maximgadelev commented on app/src/main/res/values/strings.xml
> -    <string name="to_order_registration">Перейти к оформлению</string>
Верни обратно эти строки из мастера

2022-05-16 20:50 UTC, Hukumister commented
@MariaDimukhametova ну шо там, давай уже добьем этот ПР)

2022-06-03 12:28 UTC, Hukumister submitted a review, later dismissed

2022-08-19 12:50 UTC, closed without merging