Finished task for Menu Fragment
maximgadelev/tinkoff-project pull request #6
Opened 2022-03-23 16:29 UTC by maximgadelev

2022-03-25 05:37 UTC, Hukumister requested changes

2022-03-25 05:37 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/data/MenuRepository.kt
> +    private val mapper: EntityMapper,
Этот мапер нужен только на Presentation слое, тут это лишнее

2022-03-25 05:37 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/data/MenuRepository.kt
> +    private val testApiImpl: TestApiImpl
Здесь должен быть Api интерфейс, а не конкретная реализация, почитай про принципы SOLID, в частности что такое Dependency Inversion

2022-03-25 05:37 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/data/TestApiImpl.kt
> +    override suspend fun getCategories() {
Давай все таки, если делаем тестовую реализацию интерфейса, но реализуем сразу все методы

2022-03-25 05:37 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/data/TestRepo.kt
> +object TestRepo {
Вот этот object, по сути лишнее, его методы можно перенести в TestApiImpl

2022-03-25 05:37 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/data/TestApiImpl.kt
> +class TestApiImpl(
Я бы заменил название на StubApi

2022-03-25 05:37 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/ui/MenuFragment.kt
> +    private  val viewModel by lazy {
Давай тут с lazy лучше заменим на делегат из activity-ktx:
```val viewModel: MenuViewModel by viewModels()```

2022-03-25 05:37 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/ui/MenuFragment.kt
> +        val titleDecoration = SpaceRuleItemDecoration.Builder<Item>()
Лучше вынести всю настройку списка в отдельную функцию

2022-03-25 05:37 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/ui/MenuFragment.kt
> +            .renderer(Item.SnapItem::class, SnapRenderer("Square_200"))
Вот эти строки, давай заменим на enum, такие строки лучше избегать можно легко ошибиться

2022-03-25 05:37 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/ui/MenuViewModel.kt
> +            resultList += Item.SnapItem(menuRepository.getPromotionsSnapRenderItem())
Мапер должен быть на этом уровне, т.е использоваться тут

2022-03-25 05:37 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/ui/MenuViewModel.kt
> +    fun getAllItem() {
По сути, это можно просто вызывать в Init блоке самой MenuViewModel

2022-03-25 05:37 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/ui/MenuViewModel.kt
> +class MenuViewModel(
MenuViewModel -> MainViewModel

2022-03-25 05:37 UTC, Hukumister commented on app/src/main/res/animator/button_elevation.xml
>  <selector xmlns:android="http://schemas.android.com/apk/res/android">
А зачем этот button_elevation судя по названию это что-то вроде тени? Давай-те анимации пока не будет добавлять и пока делаем все стандартное

2022-03-25 05:37 UTC, Hukumister commented on app/src/main/res/values/colors.xml
> +
Лишние переносы строк

2022-03-25 18:43 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/data/StubApi.kt
> +    private val price = 5999
Все это выносим константы на уровне файла

2022-03-25 18:45 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/MainViewModel.kt
> +init {
тут поехало форматирование

2022-03-25 18:47 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/ui/MenuFragment.kt
> +//            addOnScrollListener(object : RecyclerView.OnScrollListener() {
Done

2022-03-25 18:47 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/data/MenuRepository.kt
> +    private val mapper: EntityMapper,
Done

2022-03-25 18:47 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/data/MenuRepository.kt
> +    private val testApiImpl: TestApiImpl
Done

2022-03-25 18:47 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/data/TestApiImpl.kt
> +class TestApiImpl(
Done

2022-03-25 18:48 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/ui/MenuFragment.kt
> +    private  val viewModel by lazy {
Done

2022-03-25 18:48 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/ui/MenuFragment.kt
> +        val titleDecoration = SpaceRuleItemDecoration.Builder<Item>()
Done

2022-03-25 18:49 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/ui/MenuViewModel.kt
> +    fun getAllItem() {
Done

2022-03-25 18:49 UTC, maximgadelev commented on app/src/main/res/values/colors.xml
> +
Done

2022-03-25 18:52 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/renderer/ProductCardRenderer.kt
> +            itemView.productPriceTextView.text = item.price.toString() + " Р"
конкатенацию строк желетельно делать в мапере, чтобы тут уже была готова строка

2022-03-25 18:54 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/renderer/ThreePromotionsCardRenderer.kt
> +class ThreePromotionsCardRenderer<Item>(isLong: String) :
Мне кажется или SnapRenderer очень сильно похож на этот Renderer? Мб просто сделать настройку Boolean на входе который показывает использовать SnapHelper или нет

2022-03-25 18:56 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/renderer/ThreePromotionsCardRenderer.kt
> +class ThreePromotionsCardRenderer<Item>(isLong: String) :
И убери эту строку в конструкторе, тебя самого не смущает, переменная с названием isLong типа String 😀?

2022-03-25 18:57 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/utils/Item.kt
> +sealed class Item:ComparableItem {
Перетащи этот класс в menu/ui и преименнуй в MainItem

2022-03-25 18:57 UTC, Hukumister commented on app/src/main/res/layout/item_static_three_promotion_list.xml
> +
Лишние строки

2022-03-26 00:53 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/data/TestApiImpl.kt
> +    override suspend fun getCategories() {
Done

2022-03-26 00:53 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/data/StubApi.kt
> +    private val price = 5999
Done

2022-03-26 00:53 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/data/StubApi.kt
> +@SuppressWarnings("EmptyFunctionBlock", "MagicNumber", "MaxLineLength")
Done

2022-03-26 00:53 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/data/StubApi.kt
> +    override suspend fun getCategories() {
Done

2022-03-26 00:53 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/MainViewModel.kt
> +init {
Done

2022-03-26 00:53 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/data/mapper/EntityMapper.kt
> +class EntityMapper {
Done

2022-03-26 00:53 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/MainViewModel.kt
> +            resultList += Item.SnapItem(entityMapper.mapPromotionToSnapRenderItem(menuRepository.getPromotions()))
Done

2022-03-26 00:54 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/MenuFragment.kt
> +private fun createMainList(){
Done

2022-03-26 00:54 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/renderer/ProductCardRenderer.kt
> +            itemView.productPriceTextView.text = item.price.toString() + " Р"
Done

2022-03-26 00:54 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/utils/PromotionItemSize.kt
> +    SQUARE_200("Square_200"), SQUARE_100("Square_100"), LONG("Long")
Done

2022-03-26 00:54 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/renderer/ThreePromotionsCardRenderer.kt
> +class ThreePromotionsCardRenderer<Item>(isLong: String) :
Done

2022-03-26 00:54 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/utils/Item.kt
> +sealed class Item:ComparableItem {
Done

2022-03-26 00:55 UTC, maximgadelev commented on app/src/main/res/layout/item_static_three_promotion_list.xml
> +
Done

2022-03-26 12:14 UTC, Hukumister requested changes

2022-03-26 12:14 UTC, Hukumister commented on app/src/main/AndroidManifest.xml
> +<uses-permission android:name="android.permission.INTERNET"/>
Тут форматирование поехало

2022-03-26 12:14 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/data/Api.kt
> +    @GET()
```kotlin 
@GET("categories")
```

2022-03-26 12:14 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/data/Api.kt
> +    @GET()
```kotlin 
@GET("products")
```

2022-03-26 12:14 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/data/Api.kt
> +    suspend fun getProfileInfo():Profile
```kotlin 
@GET("profileInfo")
```

2022-03-26 12:14 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/data/Api.kt
> +    @GET()
```kotlin 
@GET("promotions")
```

2022-03-26 12:14 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/MainViewModel.kt
> +        getItems()
getItems -> onViewCreated

Названия в ViewModel лучше давать в соотвествии колбэкам. Другим словами, это методы которые на что-то реагируют, а значит семантика названий должна начинаться с on например:

`onViewCreated ()` , `onSubmitButtonClick ()`, `onListItemClick ()`

2022-03-26 12:14 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/MainViewModel.kt
> +            val itemProvider = MenuItemProvider(promotions, products, entityMapper)
MenuItemProvider инициализируй как поле в ViewModel, а то получается ты создаешь его каждый раз когда происходит запрос.

И тут же promotions и products должны быть аргументами метода getItemList

2022-03-26 12:14 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/MenuFragment.kt
> +            viewModel.item.onEach {
Вот это лучше вынести обратно в onViewCreated, т.к не относится с созданию списка

2022-03-26 12:14 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/renderer/PromotionRender.kt
> +class PromotionRender<Item>(size: String) : ItemBaseRenderer<Item, RenderContract>() {
Передавай сюда не строку, а сразу Enum

2022-03-26 12:14 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/renderer/SnapRenderer.kt
> +class SnapRenderer<Item>(size: String, private val isSnap: Boolean) :
```kotlin
class SnapRenderer<Item>(
    size: String, 
    private val isSnap: Boolean
) : ItemBaseRenderer<Item, RenderContract>(), ClickableRenderer 
```

2022-03-26 12:14 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/utils/MenuItemProvider.kt
> +class MenuItemProvider
```kotlin
class MenuItemProvider(
     private val promotions: List<Promotion>,
     private val products: List<Product>,
     private val entityMapper: EntityMapper
 )
```

2022-03-26 12:14 UTC, Hukumister commented on app/src/main/res/animator/button_elevation.xml
>  <selector xmlns:android="http://schemas.android.com/apk/res/android">
Давай вообще удалим этот app/src/main/res/animator/button_elevation.xml

2022-03-26 14:00 UTC, maximgadelev commented on app/src/main/AndroidManifest.xml
> +<uses-permission android:name="android.permission.INTERNET"/>
Done

2022-03-26 14:00 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/data/Api.kt
> +    @GET()
Done

2022-03-26 14:00 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/data/Api.kt
> +    @GET()
Done

2022-03-26 14:00 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/data/Api.kt
> +    suspend fun getProfileInfo():Profile
Done

2022-03-26 14:01 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/data/Api.kt
> +    @GET()
Done

2022-03-26 14:01 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/MainViewModel.kt
> +        getItems()
Done

2022-03-26 14:01 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/MainViewModel.kt
> +            val itemProvider = MenuItemProvider(promotions, products, entityMapper)
Done

2022-03-26 14:01 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/MenuFragment.kt
> +            viewModel.item.onEach {
Done

2022-03-26 14:01 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/renderer/PromotionRender.kt
> +class PromotionRender<Item>(size: String) : ItemBaseRenderer<Item, RenderContract>() {
Done

2022-03-26 14:01 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/renderer/SnapRenderer.kt
> +class SnapRenderer<Item>(size: String, private val isSnap: Boolean) :
Done

2022-03-26 14:01 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/utils/MenuItemProvider.kt
> +class MenuItemProvider
Done

2022-03-27 14:37 UTC, Hukumister requested changes

2022-03-27 14:37 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/MainViewModel.kt
> +) : ViewModel(
Не переноси скобки тут, не забывай про автоформатирование студии

2022-03-27 14:37 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/MenuFragment.kt
> +                paddingVertical(30)
Обычно тут лучше не задавать обсолите цифры вроде 30 тут, сделай как в sample специальный extension Int.dp и предавай значение в dp. Потому как на разных девайсах жато будет смотреться капец как по разному если задавать просто значением

2022-03-27 14:37 UTC, Hukumister commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/renderer/PromotionRender.kt
> +        else -> 1
обычно если ты используешь Enum в when, то не нужно писать else, кажется тут даже студия должна была подсветить то, что он тут не нужен

2022-03-27 14:38 UTC, Hukumister commented
Ииии последний рывок, нужно пройтись по всему проекту и форматирование проверить, и переименовать Menu -> Main

2022-03-27 15:07 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/renderer/PromotionRender.kt
> +        else -> 1
Done

2022-03-27 15:07 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/MenuFragment.kt
> +                paddingVertical(30)
Done

2022-03-27 15:07 UTC, maximgadelev commented on app/src/main/java/ru/itis/tinkoff/project/features/menu/presentation/ui/MainViewModel.kt
> +) : ViewModel(
Done

2022-03-27 17:46 UTC, Hukumister approved these changes

2022-03-28 07:27 UTC, Hukumister approved these changes

2022-03-28 07:28 UTC, merged